Repository OpenVoiceOS/ovos-messagebus, pull requests merged in 2024-09, with the labels that each got.

#31 chore:semver_versioning
  requirements.txt
Labels: ignore-for-release

#32 fix:readme_full_path
  setup.py
Labels: fix

#29 feat(performance): configurable filter
  .github/workflows/build_tests.yml
  .github/workflows/install_tests.yml
  .github/workflows/unit_tests.yml
  README.md
  ovos_messagebus/event_handler.py
Labels: feature
